# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Mod Properties
# Per-version properties live in versions/<minecraft version>/gradle.properties

mod_id=continuity
# Base name of the built jar, which is published as <archives_name>-<mod_version>+<minecraft_version>.jar
mod_archives_name=ContinuityNeoForge
mod_name=Continuity: NeoForged
mod_license=LGPL-3.0-only
mod_version=3.0.2
mod_group_id=me.pepperbell.continuity
mod_authors=PepperCode1, aspctt
mod_description=Continuity is a NeoForge mod that allows resource packs that use the OptiFine connected textures format, OptiFine emissive textures format (only for blocks and item models), or OptiFine custom block layers format to work without OptiFine.
